services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: facareceita
      POSTGRES_PASSWORD: facareceita
      POSTGRES_DB: facareceita
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5436/facareceita
      SPRING_DATASOURCE_USERNAME: facareceita
      SPRING_DATASOURCE_PASSWORD: facareceita
    depends_on:
      - db
    profiles: ["app"]

volumes:
  pgdata:
    name: faca_receita_pgdata